domain: bigbang.dev

monitoring:
  enabled: false
  namespace: monitoring

# Values in `upstream` to pass to the coder chart
upstream:
  # override back to 'coder-provisioner' so the chart doesn't refer to itself as 'upstream'
  nameOverride: coder-provisioner

  coder:
    image:
      repo: "registry1.dso.mil/ironbank/coder/coder-enterprise/coder-service-2"
      tag: "2.20.3"
      
      # coder.image.pullPolicy -- The pull policy to use for the image. See:
      # https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
      pullPolicy: IfNotPresent
      # coder.image.pullSecrets -- The secrets used for pulling the Coder image from
      # a private registry.
      pullSecrets:
        - name: "private-registry"
